
package com.tax.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-22T15:47:38.136+08:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "InterException", targetNamespace = "http://webservice.tax.com/")
public class InterException_Exception extends Exception {

    private InterException interException;

    public InterException_Exception() {
        super();
    }

    public InterException_Exception(String message) {
        super(message);
    }

    public InterException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InterException_Exception(String message, InterException interException) {
        super(message);
        this.interException = interException;
    }

    public InterException_Exception(String message, InterException interException, Throwable cause) {
        super(message, cause);
        this.interException = interException;
    }

    public InterException getFaultInfo() {
        return this.interException;
    }
}
