package com.tax.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-22T15:47:38.194+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://webservice.tax.com/", name = "IVatiWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IVatiWebService {

    @WebMethod
    @RequestWrapper(localName = "service", targetNamespace = "http://webservice.tax.com/", className = "com.tax.webservice.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://webservice.tax.com/", className = "com.tax.webservice.ServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String service(
            @WebParam(name = "data", targetNamespace = "")
                    String data
    ) throws InterException_Exception;
}
