package com.tax.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-22T15:47:38.217+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "VatiWebService",
                  wsdlLocation = "http://dzfp.chinazxt.com/vati/webservice/VatiWebService?wsdl",
                  targetNamespace = "http://webservice.tax.com/")
public class VatiWebService extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.tax.com/", "VatiWebService");
    public final static QName VatiWebServiceImplPort = new QName("http://webservice.tax.com/", "VatiWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://dzfp.chinazxt.com/vati/webservice/VatiWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VatiWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://dzfp.chinazxt.com/vati/webservice/VatiWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VatiWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VatiWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VatiWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VatiWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VatiWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VatiWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IVatiWebService
     */
    @WebEndpoint(name = "VatiWebServiceImplPort")
    public IVatiWebService getVatiWebServiceImplPort() {
        return super.getPort(VatiWebServiceImplPort, IVatiWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVatiWebService
     */
    @WebEndpoint(name = "VatiWebServiceImplPort")
    public IVatiWebService getVatiWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(VatiWebServiceImplPort, IVatiWebService.class, features);
    }

}
